### ISSUE TITLE
Outside comment is not found

### ISSUE THREAD

**Issue by cakeinpanic** [Aratramba/html-comments#1]
Hello1
If my html looks like

```
<!-- comment1 -->
<div>content
    <!-- comment3 -->
</div>
<!-- comment2 -->
```

comment1 and comment2 are not found

**Comment by Aratramba** [comment]
I guess it needs a root node, so it works if you wrap it inside a tag (body, div, whatever). Is that an option?

``` html
<body>
<!-- comment1 -->
<div>content
    <!-- comment3 -->
</div>
<!-- comment2 -->
</body>
```

**Comment by cakeinpanic** [comment]
I want to parse external files and their authors don't know about this requirement)

this bug appeared because `cheerio` somehow doesn't parse root comments or doesn't set its type to `comment`, i spent 5 minutes but couldn't fix it

**Comment by Aratramba** [comment]
I've published 0.2.0 to npm. Could you check if this works for you?

**Comment by cakeinpanic** [comment]
No, it doesn't help(

**Comment by cakeinpanic** [comment]
Fix looks for html tag, but my templates might not have it(it's angular components)

Maybe you should wrap everything in a div, no matter what's inside of a template?

**Comment by cakeinpanic** [comment]
Also suggest to let pass file path OR file contents to prevent double file reading if it have been done already

**Comment by Aratramba** [comment]
> Fix looks for html tag, but my templates might not have it(it's angular components)

Are you sure you have the right version now? I've added tests where no html tag is present and these work fine. https://github.com/Aratramba/html-comments/tree/master/test/fixtures

> Also suggest to let pass file path OR file contents to prevent double file reading if it have been done already

This is already possible through `htmlcomments.load('<div></div>')`. Double file reading is something that would have to be managed outside of this package.

**Comment by Aratramba** [comment]
0.3.0 is on npm with the fix you suggested.
